job_name: act_daniel4
output_dir: outputs/train/act_daniel4
num_workers: 12
batch_size: 16    
steps: 150000          # 10x mehr als vorher → stabilere Policy
eval_freq: 1000        # alle 1k Steps evaluieren (nicht zu oft, spart Zeit)
log_freq: 200
save_checkpoint: True
seed: 42               # Reproduzierbarkeit
dataset:
  repo_id: AIR-AUDI/abb_pick_place_all
policy:
  type: act
  push_to_hub: False
  chunk_size: 20
  n_action_steps: 10
  device: cuda
  repo_id: AIR-AUDI/act_daniel4
# Optimizer (fein konfiguriert)
optimizer:
  type: adamw
  lr: 1e-4
  weight_decay: 1e-4
  grad_clip_norm: 1.0
  betas: [0.9, 0.95]
  eps: 1e-8

# Learning Rate Scheduler
scheduler:
  type: cosine_decay_with_warmup
  num_warmup_steps: 2000
  num_decay_steps: 150000
  peak_lr: 1e-4
  decay_lr: 1e-6

# Evaluation
eval:
  n_episodes: 32
  batch_size: 16
  use_async_envs: false

# Weights & Biases
wandb:
  enable: True
  project: lerobot
  entity: plab
  mode: offline
  run_id: act_daniel4

# Set export WANDB_BASE_URL=http://localhost:8080
# WandB Choise: 2
# Enter API key


# docker stop unruffled_wilbur
# local-757701108d7638f08898901d1faa3087bc4c9ed2
# local-757701108d7638f08898901d1faa3087bc4c9ed2