job_name: act_abb_dataset_2_run3
output_dir: outputs/train/act_abb_dataset_2_run3
num_workers: 16
batch_size: 16
steps: 20000
eval_freq: 100
log_freq: 200
save_freq: 2500
save_checkpoint: True
dataset:
  repo_id: AIR-AUDI/abb_dataset_2
policy:
  type: act
  push_to_hub: False
  device: cuda
  repo_id: AIR-AUDI/act_abb_dataset_2_run3
  chunk_size: 20
  n_action_steps: 3
  n_obs_steps: 1
wandb:
  enable: True
  project: abb
  entity: daniels-team
  mode: offline
  run_id: act_abb_dataset_2_run3