job_name: smolvla_abb_dataset_2_run1
output_dir: outputs/train/smolvla_abb_dataset_2_run1
num_workers: 12
batch_size: 16
steps: 50000          
eval_freq: 1000
log_freq: 200
save_freq: 2500
save_checkpoint: True
dataset:
  repo_id: AIR-AUDI/abb_dataset_2
policy:
  type: smolvla
  push_to_hub: False
  device: cuda
  repo_id: AIR-AUDI/smolvla_abb_dataset_2_run1
# Weights & Biases
wandb:
  enable: True
  project: abb
  entity: daniels-team
  mode: offline
  run_id: smolvla_abb_dataset_2_run1